src/Authentification/PasswordDialog.vala
Uniform Resource Locator (URL)
=> Capitalisation of "URL"

plugins/Methods/Password/PasswordProvider.vala, plugins/Providers/Facebook/Plugin.vala, plugins/Providers/Facebook/facebook.vala, plugins/Providers/FastMail/fastmail.vala, plugins/Providers/Google/Plugin.vala, plugins/Providers/Google/google.vala, plugins/Providers/Microsoft/Plugin.vala, plugins/Providers/Microsoft/microsoft.vala, plugins/Providers/Yahoo/yahoo.vala, src/Account.vala, src/AccountsManager.vala, src/Authentification/Dialog.vala, src/Authentification/DialogService.vala, src/Authentification/Key.vala, src/Authentification/MailDialog.vala, src/Authentification/PasswordDialog.vala, src/Authentification/RequestInfo.vala, src/Authentification/RequestQueue.vala, src/Authentification/Server.vala, src/Authentification/WebDialog.vala, src/MethodPlugin.vala, src/OnlineAccounts.vala, src/PluginManager.vala, src/PlugsManager.vala, src/ProviderPlugin.vala, src/Translation.vala, src/Views/ACListBox.vala, src/Views/AccountView.vala, src/Views/SourceSelector.vala
Updates fsf address in license headers
=> Update fsf address

data/Flickr/flickr.vala, data/Google/config.vala, plugins/OAuth-Subplugins/Microsoft/config.vala, plugins/Providers/Facebook/facebook.provider, plugins/Providers/Google/google.provider, plugins/Providers/Microsoft/microsoft.provider, plugins/Providers/Yahoo/yahoo.provider
Removes HTTP schemes, as mentioned in #1
=> Remove HTTP schemes

src/Authentification/WebDialog.vala
* Bump copyright header
* Infobar to bottom so cancel action is in the action area for linear workflows
* explicitly mark variables as private
* Organize
* Get rid of extra eventbox
=> WebDialog: misc cleanup

src/NewAccountDialog.vala
=> NewAccountDialog: Add basic search for providers

src/Views/SourceSelector.vala
Change pages when the row is selected instead of activated. Makes navigating with the keyboard consistent with other plugs
=> SourceSelector: change pages when row selected

src/Authentification/WebDialog.vala
=> Make target=blank links open in external browser

data/onlineaccounts.appdata.xml.in
For better display in Feedback and AppCenter
=> AppData: Add "Settings" to name

src/Authentification/AbstractAuthDialog.vala
=> AbstractAuthDialog: Fix action area margin

src/Plug.vala
Fixes #108 
Other code style while we're here
=> Plug: Correctly use overlay.add

src/MainView.vala, src/Widgets/AccountMenuItem.vala, src/meson.build
=> Create AccountMenuItem class

src/Dialogs/CaldavDialog.vala
Further simplification can be done, but this does the least to get rid of FoundCalender and simply use E.Source
=> CaldavDialog: Replace FoundCalendar with E.Source

src/Dialogs/CaldavDialog.vala
set can/has/activates default so that pressing enter in entries activates the next button
=> CaldavDialog: set default button for views

debian/control, debian/copyright, debian/pantheon-online-accounts-plugin-facebook.install, debian/pantheon-online-accounts-plugin-fastmail.install, debian/pantheon-online-accounts-plugin-google.install, debian/pantheon-online-accounts-plugin-lastfm.install, debian/pantheon-online-accounts-plugin-mail.install, debian/pantheon-online-accounts-plugin-microsoft.install, debian/pantheon-online-accounts-plugin-yahoo.install, debian/switchboard-plug-online-accounts.install
This should get daily builds going
=> Update Packaging for Rewrite

src/Dialogs/CaldavDialog.vala
This fixes saving credentials for caldav. Part of #172
=> Remember Auth for CalDAV

po/fi.po
A \r in the file makes Weblate error
=> i10n: Allow Weblate to handle the finnish language file

src/AccountsModel.vala
=> Hide local_mbox account

src/MainView.vala
Fixes a tiny annoyance by automatically close the add account popover when a button is clicked. TBH I have no clue why Gtk does not close the popover automatically anyways.
=> Popdown Popover when a button is clicked

src/Dialogs/Imap/ImapDialog.vala
Fixes https://github.com/elementary/mail/issues/620
=> Add support for well known google folders

data/onlineaccounts.appdata.xml.in, meson.build
Some strings changed recently, so I'm not sure if we wanna wait a couple days for translations, but otherwise I think this is good to go
=> Release 6.1.0

data/onlineaccounts.appdata.xml.in, src/Dialogs/Imap/ImapDialog.vala, src/Dialogs/Imap/ImapLoginPage.vala, src/Dialogs/Imap/ImapSavePage.vala, src/MainView.vala
Partial fix for https://github.com/elementary/switchboard-plug-onlineaccounts/issues/201 by providing a possibility to edit a mail account.
Can implement a quite similar approach for CalDAV.
=> New feature: Edit mail account

src/Dialogs/CaldavDialog.vala, src/Dialogs/Imap/ImapDialog.vala
Adds key release event handlers to close a dialog when ESC key is pressed.
=> Fixes #210: Close dialog on ESC key release

src/Dialogs/Imap/ImapDialog.vala, src/Dialogs/Imap/ImapLoginPage.vala, src/Dialogs/Imap/ImapSavePage.vala
=> ImapDialog: set can/has/activates default

data/onlineaccounts.appdata.xml.in, meson.build
https://github.com/elementary/switchboard-plug-onlineaccounts/compare/6.2.0...main
=> Release 6.2.1

data/onlineaccounts.appdata.xml.in, meson.build
=> Release 6.5.0

.github/workflows/ci.yml, meson.build, src/Dialogs/CaldavDialog.vala, src/Dialogs/Imap/ImapDialog.vala, src/Dialogs/Imap/ImapLoginPage.vala, src/Dialogs/Imap/ImapSavePage.vala, src/MainView.vala, src/Plug.vala, src/Widgets/AccountMenuItem.vala, src/Widgets/ValidationMessage.vala, src/meson.build
Is basically ready but I'm not sure whether this should be merged or how it was handled with the other plugs because AFAIK merging this will block all releases from main for this until all plugs are ported which can only happen in OS8?
=> Port to GTK4

debian/changelog, debian/control, debian/copyright
Keeps GTK4 and GTK3 versions parallel installable
=> Packaging: Gtk4

.github/workflows/ci.yml
Fixes the CI for Fedora is failing.
=> Actions: Fix build for Fedora

src/Dialogs/CaldavDialog.vala, src/Dialogs/Imap/ImapDialog.vala, src/Widgets/PagedDialog.vala, src/meson.build
DRY some dialog code and add a widget with documentation and well-defined API
=> Widgets: Add PagedDialog

meson.build, src/Dialogs/CaldavDialog.vala
We're on 3.52.3 in Noble and we no longer build for Jammy :shrug:
=> Bump EDS requirement
