- plugins/Providers/FastMail/fastmail-mail.service
This fixes #34 by setting new servers addresses for Fastmail. New servers addresses from here
https://www.fastmail.com/help/technical/servernamesandports.html?u=dcb0415a
> Update fastmail server addresses

- src/OnlineAccounts.vala
This isn't used anywhere in the Plug class.
> Remove unneded assign

- src/Authentification/RequestQueue.vala
- src/Plug.vala
* Since all the account add/remove stuff is done in a dialog there's no case left where we care to transition
* Since we always switch to main when `account_selected ()` is triggered, put that at the end of that method
* We don't need to switch to main when an account is added since `show_next_process` is called whenever we add an account which requests a switch to the right page
> Plug: Remove redundant stack switch calls

- src/Views/AccountView.vala
("Applications" is used frequently elsewhere).
> Spelling: No installed apps make use of

- po/POTFILES
- src/Authentification/AbstractAuthView.vala
- src/Authentification/MailDialog.vala
- src/Authentification/PasswordDialog.vala
- src/Authentification/RequestQueue.vala
- src/Authentification/WebDialog.vala
- src/NewAccountDialog.vala
- src/Plug.vala
- src/meson.build
Dialog is a bad class name and doesn't indicate what this class is actually for.
AbstractAuthView tells us that this class is:
* An Abstract class
* A view that shows authentication
* Not actually a Gtk.Dialog subclass
> Rename Dialog to AbstractAuthView

- src/Authentification/AbstractAuthView.vala
- src/Authentification/MailDialog.vala
- src/Authentification/PasswordDialog.vala
- src/Authentification/WebDialog.vala
This seems unused by almost all provider login views
> Dialog: Remove refresh_captcha

- src/Authentification/MailDialog.vala
* Explicitly scope variables
* GObject-style construction
* Granite.HeaderLabel
* Granite Style constants
* row_spacing instead of extra margins
* Use a Revealer instead of making SMTP credentials insensitive
> MailDialog: misc cleanups

- data/meson.build
- meson.build
- providers/Facebook/meson.build
- providers/Google/meson.build
- providers/Microsoft/meson.build
- providers/meson.build
- src/meson.build
On NixOS all packages are installed into their own immutable prefix.
Because of this get_pkgconfig_variable will return a
path from within the package's prefix and we cannot write to it.
By using define_variable we can replace the respective directory
to be from the paths from meson.  This should have no affect
on elementaryOS.
>  build: use define_variable with pkgconfig paths

- src/Plug.vala
Sometimes an account is added because of a failure to delete and not because the dialog has closed. In this case, the dialog is already null and we get an error about trying to destroy a null object
Also remove this extra `deletable`
> Plug: Only try to destroy dialog if it's non-null

- src/Authentification/OAuthView.vala
> Fix argument of callback for WebKit.WebView.load_failed()

- src/Dialogs/CaldavDialog.vala
Fixes #155 
This PR is a work in progress:
> CalDAV: Save account information

- src/AccountsModel.vala
- src/MainView.vala
Fixes #164 by adding support for auto-updating the account list. For this to work, we need to keep the `E.SourceRegistryWatcher` instances alive. Please note: After adding a CalDAV backend, the calendar items do appear in the accounts list as well for some strange reason. Not found a solution yet for this unwanted side effect - but other than that it works quite well.
> Auto Update Account List

- src/Dialogs/Imap/ImapDialog.vala
- src/Dialogs/Imap/ImapLoginPage.vala
This PR fixes the Mail setup in Online Accounts by introducing two changes:
1. To completely configure a mail account we need three sources in EDS
[According to the code in Evolution](https://gitlab.gnome.org/GNOME/evolution/-/blob/master/src/mail/e-mail-config-summary-page.c#L695-698), we need 3 sources to completely configure a mail account. Until now we only used two. The first commit of this PR fixes this. This potentially fixes #172 as well, can you please verify @danrabbit?
2. The second commit of this PR fixes #181 
The change handler was simply never executed in code if the user did not change the name - therefore the passed string was never set. The commit changes this by setting the initial state to the correct value.
> Fix Mail setup

- src/Dialogs/Imap/ImapDialog.vala
This PR potentially fixes https://github.com/elementary/mail/issues/620 by pre-configuring well known mail folders when a new IMAP account is added in Online Accounts:
**Before**
**After**
> Configuring well known folder URIs

- data/onlineaccounts.appdata.xml.in
- src/Dialogs/Imap/ImapDialog.vala
Fixes #203 and superseds #207.
@danrabbit thinking about this a bit more I found a more elegant solution to the problem by simply probing for LOGIN and PLAIN auth methods. This way we do not need any additional form inputs. Also I don't think most users are aware what those authentication mechanisms are anyway.
> Auto detect auth mechanism for IMAP and SMTP

- data/onlineaccounts.appdata.xml.in
- src/Dialogs/CaldavDialog.vala
Make sure we set can/has/activates default everywhere so that you can always navigate forward by pressing "enter".
While we're here, set "back" to invisible instead of insensitive since there's nothing a user can do to make it sensitive on the "Success" page
> CaldavDialog: set can/has/activate default

- src/Dialogs/CaldavDialog.vala
This PR fixes an synchronization error with calendar subscriptions (Screenshot from Evolution):
The root cause here is, that we can't possibly know the credentials used to subscribe to a calendar from the 3rd party server. Therefore, if the reported WebDAV url contains another host than we are trying to connect to, we are going to ignore this calendar source and require the user to add the subscription in the corresponding app.
This fix is related to https://github.com/elementary/calendar/issues/700
> Ignore Calendar Subscriptions

- data/onlineaccounts.appdata.xml.in
- src/Dialogs/Imap/ImapDialog.vala
This PR makes sure we set the refresh interval for IMAP mail boxes. This is usefull for https://github.com/elementary/mail/pull/679 which uses this value to schedules checking for new mails per account based upon this value.
> Set refresh interval for IMAP

- data/onlineaccounts.appdata.xml.in
- src/Dialogs/Imap/ImapDialog.vala
This PR avoids having the auth methods hard coded and retrieves the supported ones from the corresponding Camel method. This potentially fixes an issue for users not able to add IMAP accounts through System Settings.
In this PR we also make sure we reset a potential error only if we were able to succesfully authenticate.
Potentially fixes https://github.com/elementary/mail/issues/685
> Retrieve login methods from camel

- data/onlineaccounts.appdata.xml.in
- src/Dialogs/CaldavDialog.vala
This PR fixes issues where adding/editing and removing task lists weren't possible in the Tasks app. All of this was due to missing information when adding the CalDAV account through Online Accounts (for details see: https://github.com/elementary/tasks/issues/269#issuecomment-918174238)
The changes in this PR also enables us to drop a bunch of code which is no longer needed, because EDS is now capable to discover and add child sources (read "Task lists" or "Calendars") by itself.
> Caldav set calendar url of collection source

- src/Dialogs/Imap/ImapDialog.vala
With the latest gala changes dim parent wasn't working here. Give a dialog type hint to make sure it does
> ImapDialog: Set dialog type_hint to fix parenting

- data/onlineaccounts.appdata.xml.in
- src/Dialogs/Imap/ImapDialog.vala
Fixes [Add a setting to allow the user to configure the interval to fetch new email](https://github.com/elementary/switchboard-plug-onlineaccounts/issues/223)
Fixes [Configurable refresh period](https://github.com/elementary/mail/issues/752)
> Allow to configure the interval in minutes to fetch new email

- data/onlineaccounts.appdata.xml.in
- src/Dialogs/CaldavDialog.vala
This PR adds offline support to task lists and calendars of newly configured CalDAV accounts. You can check the functionality by starting Evolution (installed from *.deb): `Right click > Properties` on a task list or calendar within a CalDAV account:
Please note this does not configure offline support for newly created task lists or calendars once the account is setup. This has to be fixed in Tasks or Calendar directly.
> CalDAV: Offline support for newly configured accounts

- .github/workflows/ci.yml
- meson.build
- src/Dialogs/CaldavDialog.vala
- src/meson.build
> Add support for evolution-data-server 3.45+ / libsoup-3

- src/Dialogs/Imap/ImapDialog.vala
Fix a freeze/crash when a server can be reached but doesn't respond, e.g. [smtp.t-online.de](https://smtp.t-online.de). It will try to setup the mail account forever but at least now it can be cancelled.
> ImapDialog: Fix freeze when a server sends no response

- src/Dialogs/Imap/ImapDialog.vala
The original motivation behind this was to store the `use-real-trash-path` and `real-trash-path` keys as well as the `use-real-junk-path` and `real-junk-path` keys in order to fix #232 as well as elementary/mail#749 and in preparation for elementary/mail#881
However I think it is better to not cherry pick keys to store as done previously but rather try to store all keys.
So now all keys for all source types except `Collection` (we don't use `Collection` sources) will be stored. 
Inspiration for that was how evolution does it [here](https://gitlab.gnome.org/GNOME/evolution/-/blob/master/src/libemail-engine/e-mail-store-utils.c#L406).
Partly fixes #232 
Closes elementary/mail#749
> ImapDialog: Store most initial setup keys

- .github/workflows/ci.yml
We build granite7 because that is [not in fedora repositories](https://repology.org/project/granite/versions), but since this plug hasn't ported to gtk4 yet there should be no reason to break CI due to this (though the case here is simple as missing sassc).
With the same reason there should be no need to install libadwaita right now.
(We will have to revisit this file anyway when we port things to gtk4 I assume, since the switchboard version is hardcoded to 6.0.2)
> CI: unbreak fedora

- data/onlineaccounts.metainfo.xml.in
The correct icon name is `gettext_name + '.svg'`, i.e. `io.elementary.settings.onlineaccounts`.
This should fix the broken icon in Feedback:
> Metainfo: Correct stock icon name

- data/gresource.xml
Make sure we have a fallback for if an online account type is added that we don't ship an icon for:
> Add fallback icon
